training_pipeline_config :
  pipeline_name : housing 
  artifact_dir : artifact

data_ingestion_config :
  data_ingestion_dir : 'data_ingestion'
  dataset_download_url: https://github.com/pramodkhavare/Datasets/raw/main/samsun_data.zip
  tgz_download_dir : tgz_data
  raw_data_dir : raw_data
  ingested_dir : ingested_data 
  ingested_train_dir : train 
  ingested_test_dir : test